export const CUSTOMERS_TABLE = 'CUSTOMERS_TABLE';
export const CALLS_TABLE = 'CALLS_TABLE';
export const OPERATORS_TABLE = 'OPERATORS_TABLE';
export const CALLS_DURATION_TABLE = 'CALLS_DURATION_TABLE';
