export const CUSTOMERS_TABLE = 'CUSTOMERS_TABLE';
export const SUPERADMIN_COMPANIES_TABLE = 'SUPERADMIN_COMPANIES_TABLE';
export const CALLS_TABLE = 'CALLS_TABLE';
export const OPERATORS_TABLE = 'OPERATORS_TABLE';
export const CALLS_DURATION_TABLE = 'CALLS_DURATION_TABLE';
export const CALLS_FEEDBACK_TABLE = 'CALLS_FEEDBACK_TABLE';
