apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-video-static
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod-video-static
  template:
    metadata:
      labels:
        app: prod-video-static
    spec:
#      nodeSelector:
#        env: applications
      containers:
      - name: prod-video-static
        image: xyziesprodregistry.azurecr.io/vsp-fe-video-prod:0.0.0.0
        resources:
          requests:
            cpu: 150m
            memory: 512Mi
          limits:
            cpu: 200m
            memory: 1024Mi
        ports:
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: prod-video-static
  namespace: prod
spec:
  ports:
  - protocol: "TCP"
    port: 8090
    targetPort: 8090
    name: "http"
  selector:
    app: prod-video-static
  clusterIP: 10.0.183.90
