import i18n from '@/i18n';

export const getCustomersTableColumns = () => [
  {
    name: 'company',
    field: 'company',
    title: i18n.t('Company'),
    width: '300px',
  },
  {
    name: 'contactPerson',
    field: 'contactPerson',
    class: 'text',
    title: i18n.t('Contact person'),
  },
  {
    name: 'email',
    field: 'email',
    fieldType: 'email',
    class: 'text',
    title: i18n.t('Email'),
  },
  {
    name: 'phone',
    field: 'phone',
    class: 'text',
    title: i18n.t('Phone'),
    width: '150px',
  },
  {
    name: 'lastPayment',
    field: 'lastPayment',
    fieldType: 'lastPayment',
    title: i18n.t('Last payment'),
  },
  {
    name: 'amount',
    field: 'amount',
    title: i18n.t('Amount'),
    class: 'number',
    width: '100px',
  },
  {
    name: 'additional',
    field: null,
    fieldType: 'additional',
    title: '',
    width: '100px',
  },
];

export const getCallsTableColumns = () => [
  {
    name: 'date',
    field: 'date',
    fieldType: 'date',
    title: i18n.t('Date'),
    class: 'text',
  },
  {
    name: 'operator',
    field: 'operator',
    class: 'text',
    title: i18n.t('Operator'),
  },
  {
    name: 'retailers',
    field: 'retailers',
    class: 'text',
    title: i18n.t('Retailers'),
  },
  {
    name: 'type',
    field: 'type',
    fieldType: 'type',
    class: 'text',
    title: i18n.t('Type'),
    width: '100px',
  },
  {
    name: 'disposition',
    field: 'disposition',
    fieldType: 'disposition',
    class: 'text',
    title: i18n.t('Disposition'),
  },
  {
    name: 'waitTime',
    field: 'waitTime',
    fieldType: 'waitTime',
    title: i18n.t('Wait time'),
    class: 'number',
  },
  {
    name: 'duration',
    field: 'duration',
    fieldType: 'duration',
    title: i18n.t('Duration'),
    width: '100px',
  },
  {
    name: 'rating',
    field: 'rating',
    fieldType: 'rating',
    title: i18n.t('Rating'),
    width: '60px',
  },
  {
    name: 'status',
    field: 'status',
    fieldType: 'status',
    title: i18n.t('Status'),
    class: 'text',
    width: '100px',
  },
  {
    name: 'clientFeedback',
    field: 'clientFeedback',
    fieldType: 'clientFeedback',
    title: i18n.t('Client'),
    width: '80px',
  },
  {
    name: 'operatorFeedback',
    field: 'operatorFeedback',
    fieldType: 'operatorFeedback',
    title: i18n.t('Operator'),
    width: '80px',
  },
];
