import Emitter from '@/services/Emitter';

const REMOTE_TRACKS_ADDED = 'REMOTE_TRACKS_ADDED';
const REMOTE_TRACKS_REMOVED = 'REMOTE_TRACKS_REMOVED';
const LOCAL_TRACKS_ADDED = 'LOCAL_TRACKS_ADDED';
const LOCAL_TRACKS_REMOVED = 'LOCAL_TRACKS_REMOVED';
const SCREEN_SHARED = 'SCREEN_SHARED';
const SCREEN_UNSHARED = 'SCREEN_UNSHARED';
const PARTICIPANT_CONNECTED = 'PARTICIPANT_CONNECTED';
const PARTICIPANT_DISCONNECTED = 'PARTICIPANT_DISCONNECTED';
const RECONNECTING = 'RECONNECTING';
const RECONNECTED = 'RECONNECTED';
const CONNECTED = 'CONNECTED';

export const TWILIO_EVENTS = {
  REMOTE_TRACKS_ADDED,
  REMOTE_TRACKS_REMOVED,
  LOCAL_TRACKS_ADDED,
  LOCAL_TRACKS_REMOVED,
  SCREEN_SHARED,
  SCREEN_UNSHARED,
  PARTICIPANT_CONNECTED,
  PARTICIPANT_DISCONNECTED,
  RECONNECTING,
  RECONNECTED,
  CONNECTED,
};

export default new Emitter();
