export const SET_OPERATOR_STATUS = 'SET_OPERATOR_STATUS';
export const SET_CALL_TOKEN = 'SET_CALL_TOKEN';
export const SET_CALL_DATA = 'SET_CALL_DATA';
export const SET_PENDING_CALLS_INFO = 'SET_PENDING_CALLS_INFO';
