export const SET_OPERATOR_STATUS = 'SET_OPERATOR_STATUS';
export const SET_CALL_TOKEN = 'SET_CALL_TOKEN';
export const SET_CALL_DATA = 'SET_CALL_DATA';
export const SET_CONNECTION_TO_CALL_SOCKET = 'SET_CONNECTION_TO_CALL_SOCKET';
export const SET_PENDING_CALLS_INFO = 'SET_PENDING_CALLS_INFO';
export const SET_EXTENSION_AVAILABILITY = 'SET_EXTENSION_AVAILABILITY';
