export const LOAD_ITEMS = 'LOAD_ITEMS';
export const LOAD_MORE_ITEMS = 'LOAD_MORE_ITEMS';
export const CREATE_ITEM = 'CREATE_ITEM';
export const UPDATE_ITEM = 'UPDATE_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const LOAD_CALL_TYPES_AND_DISPOSITIONS = 'LOAD_CALL_TYPES_AND_DISPOSITIONS';
export const UPDATE_DEVICE = 'UPDATE_DEVICE';
