export const LOAD_CUSTOMERS = 'LOAD_CUSTOMERS';
export const LOAD_ALL_CUSTOMERS_LENGTH = 'LOAD_ALL_CUSTOMERS_LENGTH';
export const LOAD_CALLS = 'LOAD_CALLS';
export const LOAD_ALL_CALLS_LENGTH = 'LOAD_ALL_CALLS_LENGTH';
export const LOAD_CALL_TYPES_AND_DISPOSITIONS = 'LOAD_CALL_TYPES_AND_DISPOSITIONS';
