export const LOAD_CUSTOMERS = 'LOAD_CUSTOMERS';
export const LOAD_ALL_CUSTOMERS_LENGTH = 'LOAD_ALL_CUSTOMERS_LENGTH';
export const LOAD_CALLS = 'LOAD_CALLS';
export const LOAD_ALL_CALLS_LENGTH = 'LOAD_ALL_CALLS_LENGTH';
export const LOAD_OPERATORS = 'LOAD_OPERATORS';
export const LOAD_ALL_OPERATORS_LENGTH = 'LOAD_ALL_OPERATORS_LENGTH';
