export const INSERT_ITEMS = 'INSERT_ITEMS';
export const SET_ALL_ITEMS_LOADED = 'SET_ALL_ITEMS_LOADED';
export const RESET_ITEMS = 'RESET_ITEMS';
export const CHANGE_ITEM = 'CHANGE_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const SET_ITEMS_TOTAL = 'SET_ITEMS_TOTAL';
export const SET_CALL_TYPES_AND_DISPOSITIONS = 'SET_CALL_TYPES_AND_DISPOSITIONS';
