export const INSERT_CUSTOMERS = 'INSERT_CUSTOMERS';
export const SET_ALL_CUSTOMERS_LENGTH = 'SET_ALL_CUSTOMERS_LENGTH';
export const INSERT_CALLS = 'INSERT_CALLS';
export const SET_ALL_CALLS_LENGTH = 'SET_ALL_CALLS_LENGTH';
export const INSERT_OPERATORS = 'INSERT_OPERATORS';
export const SET_ALL_OPERATORS_LENGTH = 'SET_ALL_OPERATORS_LENGTH';
