export default () => [
  {
    name: 'date',
    field: 'date',
    fieldType: 'date',
    title: 'date',
    class: 'text',
    width: '3',
    minWidth: '100px',
  },
  {
    name: 'operator',
    field: 'operator',
    class: 'text',
    title: 'operator',
    width: '4',
    minWidth: '100px',
  },
  {
    name: 'company',
    field: 'company',
    class: 'text',
    title: 'company',
    width: '4',
    minWidth: '100px',
    placeholder: '-',
  },
  {
    name: 'type',
    field: 'type',
    fieldType: 'type',
    title: 'type',
    width: '2',
    minWidth: '65px',
  },
  {
    name: 'disposition',
    field: 'operatorFeedback.disposition',
    fieldType: 'disposition',
    class: 'text',
    title: 'disposition',
    width: '2',
    minWidth: '85px',
    placeholder: '-',
  },
  {
    name: 'duration',
    field: 'duration',
    fieldType: 'duration',
    title: 'duration',
    width: '2',
  },
  {
    name: 'rating',
    field: 'rating',
    fieldType: 'rating',
    title: 'rating',
    width: '1',
    minWidth: '50px',
  },
  {
    name: 'clientFeedback',
    field: 'clientFeedback',
    fieldType: 'clientFeedback',
    title: 'client',
    width: '1',
    minWidth: '40px',
  },
  {
    name: 'operatorFeedback',
    field: 'operatorFeedback',
    fieldType: 'operatorFeedback',
    title: 'operator',
    width: '1',
    minWidth: '40px',
  },
];
