import { DEVICE_LIST_COLUMNS_SORTED } from '@/constants';

export default () => [
  {
    name: 'id',
    field: 'id',
    fieldType: 'id',
    title: 'id',
    class: 'text',
    width: '2',
    minWidth: '50px',
  },
  {
    name: 'udid',
    field: 'udid',
    fieldType: 'udid',
    class: 'text',
    title: 'udid.idfv',
    width: '2',
    minWidth: '50px',
  },
  {
    name: 'statusSince',
    field: 'statusSince',
    fieldType: 'statusSince',
    title: 'status.since',
    width: '2',
    class: 'text',
    minWidth: '80px',
  },
  {
    name: 'status',
    field: 'isOnline',
    fieldType: 'status',
    class: 'text',
    title: 'Status',
    width: '2',
    minWidth: '60px',
    sortingFieldName: DEVICE_LIST_COLUMNS_SORTED.IS_ONLINE,
    fieldHeaderType: 'sortingHeader',
  },
  {
    name: 'locationStatus',
    field: 'isInLocation',
    fieldType: 'locationStatus',
    class: 'text',
    title: 'location.status',
    width: '1',
    minWidth: '50px',
  },
  {
    name: 'comments',
    field: 'comments',
    fieldType: 'comments',
    title: 'comments',
    width: '1',
  },
  {
    name: 'branch',
    field: 'branch.branchName',
    fieldType: 'branch',
    title: 'branch.name',
    width: '2',
    class: 'text',
    minWidth: '65px',
    sortingFieldName: DEVICE_LIST_COLUMNS_SORTED.BRANCH_NAME,
    fieldHeaderType: 'sortingHeader',
  },
  {
    name: 'company',
    field: 'company.companyName',
    fieldType: 'company',
    title: 'company',
    width: '2',
    class: 'text',
    minWidth: '50px',
  },
  {
    name: 'loggedInAs',
    field: 'loggedInAs.displayName',
    fieldType: 'loggedInAs',
    title: 'logged.in.as',
    width: '1',
    class: 'text',
    minWidth: '40px',
    placeholder: '-',
  },
];
