import callsTableColumns from './callsTable';
import devicesTablecolumns from './devicesTable';
import deviceHistoryColumns from './deviceHistoryTable';
import customersTableColumns from './customersTable';
import superAdminCompaniesTableColumns from './superAdminCompaniesTable';
import superAdminOperatorsTableColumns from './superAdminOperatorsTable';
import operatorsTableColumns from './operatorsTable';
import callsDurationTableColumns from './callsDurationTable';
import callsFeedbackTableColumns from './callsFeedbackTable';
import paymentsTableColumns from './paymentsTable';

export const getCallsTableColumns = callsTableColumns;
export const getDevicesTablecolumns = devicesTablecolumns;
export const getDeviceHistoryTableColumns = deviceHistoryColumns;
export const getCustomersTableColumns = customersTableColumns;
export const getSuperadminCompaniesTableColumns = superAdminCompaniesTableColumns;
export const getSuperadminOperatorsTableColumns = superAdminOperatorsTableColumns;
export const getOperatorsTableColumns = operatorsTableColumns;
export const getCallsDurationTableColumns = callsDurationTableColumns;
export const getCallsFeedbackTableColumns = callsFeedbackTableColumns;
export const getPaymentsTableColumns = paymentsTableColumns;
