export default () => [
  {
    name: 'date',
    field: 'date',
    fieldType: 'date',
    title: 'date',
    class: 'text',
    width: '200px',
  },
  {
    name: 'type',
    field: 'type',
    fieldType: 'type',
    class: 'text',
    title: 'type',
    width: '650px',
  },
  {
    name: 'status',
    field: 'status',
    fieldType: 'status',
    class: 'text',
    title: 'status',
    width: '120px',
  },
  {
    name: 'amount',
    field: 'amount',
    fieldType: 'amount',
    class: 'number',
    title: 'amount',
    width: '100px',
  },
  {
    name: 'additional',
    field: null,
    fieldType: 'additional',
    title: '',
    width: '70px',
  },
];
