export default () => [
  {
    name: 'companyName',
    field: 'companyName',
    fieldType: 'companyName',
    title: 'retailer',
    width: '1',
    class: 'text',
    minWidth: '50px',
  },
  {
    name: 'salesRepName',
    field: 'salesRepName',
    fieldType: 'salesRepName',
    class: 'text',
    title: 'sales.rep',
    width: '1',
    minWidth: '55px',
  },
  {
    name: 'deviceName',
    field: 'deviceName',
    fieldType: 'deviceName',
    class: 'text',
    title: 'device',
    width: '1',
    minWidth: '50px',
  },
  {
    name: 'waitingDuration',
    field: 'waitingDuration',
    fieldType: 'waitingDuration',
    class: 'text',
    title: 'response.time',
    width: '1',
    minWidth: '50px',
  },
  {
    name: 'operatorName',
    field: 'operatorName',
    fieldType: 'operatorName',
    class: 'text',
    title: 'operator.name',
    width: '1',
    minWidth: '55px',
  },
  {
    name: 'acceptedAt',
    field: 'acceptedAt',
    fieldType: 'acceptedAt',
    class: 'text',
    title: 'call.duration',
    width: '1',
    minWidth: '50px',
  },
];
