export default () => [
  {
    name: 'callbacks',
    field: 'callbacks',
    fieldType: 'callbacks',
    title: '',
    width: '30px',
    minWidth: '30px',
  },
  {
    name: 'companyName',
    field: 'companyName',
    fieldType: 'companyName',
    title: 'retailer',
    width: '1',
    class: 'text',
    minWidth: '130px',
  },
  {
    name: 'salesRepName',
    field: 'salesRepName',
    fieldType: 'salesRepName',
    class: 'text',
    title: 'sales.rep',
    width: '2',
    minWidth: '230px',
  },
  {
    name: 'deviceName',
    field: 'deviceName',
    fieldType: 'deviceName',
    class: 'text',
    title: 'device',
    width: '1',
    minWidth: '140px',
  },
  {
    name: 'requestedAt',
    field: 'requestedAt',
    fieldType: 'requestedAt',
    class: 'text',
    title: 'waiting.time',
    width: '1',
    minWidth: '140px',
  },
];
