export default () => [
  {
    name: 'id',
    field: 'id',
    fieldType: 'id',
    class: 'text',
    title: 'id',
    width: '100px',
  },
  {
    name: 'company',
    field: 'company',
    title: 'company',
    width: '300px',
  },
  {
    name: 'name',
    field: 'name',
    fieldType: 'name',
    class: 'text',
    title: 'name',
    width: '250px',
  },
  {
    name: 'department',
    field: 'department',
    class: 'text',
    title: 'department',
    width: '200px',
  },
  {
    name: 'calls',
    field: 'calls',
    fieldType: 'calls',
    class: 'text',
    title: 'calls',
    width: '100px',
  },
  {
    name: 'info',
    field: 'info',
    fieldType: 'calls',
    class: 'text',
    title: 'info',
    width: '100px',
  },
  {
    name: 'help',
    field: 'help',
    fieldType: 'calls',
    class: 'text',
    title: 'help',
    width: '100px',
  },
  {
    name: 'sale',
    field: 'sale',
    fieldType: 'calls',
    class: 'text',
    title: 'sale',
    width: '100px',
  },
  {
    name: 'wrapUpTime',
    field: 'wrapUpTime',
    class: 'text',
    fieldType: 'wrapUpTime',
    title: 'wrap.up.time',
    width: '150px',
  },
  {
    name: 'rating',
    field: 'rating',
    fieldType: 'rating',
    title: 'rating',
    class: 'text',
    width: '100px',
  },
  {
    name: 'positive',
    field: 'positive',
    fieldType: 'calls',
    class: 'text',
    title: 'positive',
    width: '100px',
  },
  {
    name: 'negative',
    field: 'negative',
    fieldType: 'calls',
    class: 'text',
    title: 'negative',
    width: '100px',
  },
  {
    name: 'additional',
    field: null,
    fieldType: 'additional',
    title: '',
    width: '70px',
  },
];
