/* eslint-disable-next-line import/prefer-default-export */
export const LOAD_CALLS_ANSWERED_DATA = 'LOAD_CALLS_ANSWERED_DATA';
export const LOAD_CALLS_MISSED_DATA = 'LOAD_CALLS_MISSED_DATA';
export const GET_TENANTS_LIST = 'GET_TENANTS_LIST';
export const CHANGE_DASHBOARD_TENANT_FILTER = 'CHANGE_DASHBOARD_TENANT_FILTER';
export const CHANGE_WAITING_CALLS = 'CHANGE_WAITING_CALLS';
export const CHANGE_ACTIVE_CALLS = 'CHANGE_ACTIVE_CALLS';
