export const WAITING_CALLS_CHANGED = 'WAITING_CALLS_CHANGED';
export const ACTIVE_CALLS_CHANGED = 'ACTIVE_CALLS_CHANGED';

export const REALTIME_DASHBOARD_CALL_FINISHED = 'REALTIME_DASHBOARD_CALL_FINISHED';
export const REALTIME_DASHBOARD_CALL_ACCEPTED = 'REALTIME_DASHBOARD_CALL_ACCEPTED';
export const REALTIME_DASHBOARD_OPERATORS_STATUSES_CHANGED =
  'REALTIME_DASHBOARD_OPERATORS_STATUSES_CHANGED';

export const INSERT_DATA = 'INSERT_DATA';

export const INSERT_CALLS_ANSWERED_DATA = 'INSERT_CALLS_ANSWERED_DATA';
export const INSERT_CALLS_MISSED_DATA = 'INSERT_CALLS_MISSED_DATA';
