export const WAITING_CALLS_CHANGED = 'WAITING_CALLS_CHANGED';
export const WAITING_CALLBACKS_CHANGED = 'WAITING_CALLBACKS_CHANGED';
export const ACTIVE_CALLS_CHANGED = 'ACTIVE_CALLS_CHANGED';

export const REALTIME_DASHBOARD_CALL_FINISHED = 'REALTIME_DASHBOARD_CALL_FINISHED';
export const REALTIME_DASHBOARD_CALL_ACCEPTED = 'REALTIME_DASHBOARD_CALL_ACCEPTED';
export const REALTIME_DASHBOARD_CALLBACK_DECLINED = 'REALTIME_DASHBOARD_CALLBACK_DECLINED';
export const REALTIME_DASHBOARD_CALLBACK_ACCEPTED = 'REALTIME_DASHBOARD_CALLBACK_ACCEPTED';

export const REALTIME_DASHBOARD_OPERATORS_STATUSES_CHANGED =
  'REALTIME_DASHBOARD_OPERATORS_STATUSES_CHANGED';

export const INSERT_CALLS_ANSWERED_DATA = 'INSERT_CALLS_ANSWERED_DATA';
export const INSERT_CALLS_MISSED_DATA = 'INSERT_CALLS_MISSED_DATA';
export const INSERT_CALLBACKS_DATA = 'INSERT_CALLBACKS_DATA';
export const SET_TENANT_LIST = 'SET_TENANT_LIST';
export const SET_TENANT_ID = 'SET_TENANT_ID';

export const REALTIME_DASHBOARD_CLEAR_DATA = 'REALTIME_DASHBOARD_CLEAR_DATA';
